version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'C3xDVKmG3XbOHGA7tpoz'
    ports:
      - '15432:5432'
    volumes:
      - /home/gabriel/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'glangort@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'C3xDVKmG3XbOHGA7tpoz'
    ports:
      - '16543:80'
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
